### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by Sancho-git** [Korto19/Multiple-Maps#1]
Hi Giulio. 
I would like to suggest you to upload some sample data to test your plug-in. 

Great Job!

Sancho.

**Comment by Korto19** [comment]
Hi, thanks for your feedback,  coming soon
Best regards

⁣Inviato da BlueMail ​

Il giorno 14 mar 2021, 18:31, alle ore 18:31, Sancho-git ***@***.***> ha scritto:
